### PR TITLE
Remove Type::detect_has_vtable_cycle.

### PR DESCRIPTION
**Pull request by SirVer**
After some discussion in #765 we do not think anymore that this can ever be true.

### CODE REVIEW

**Comment by emilio** [comment]
Can you squash the commits please? Thanks!

**Comment by SirVer** [comment]
@emilio Done. 

My 2c: In my humble opinion this should be done by the merge bot. It is quite useful to keep the history of the commits in the related PR to see the development of the discussion and GitHub does not deal well with rebasing.

GitHubs own merge tools actually allow for that - squashing everything into one commit on merge. The mergebot could do that too - the only question is which commit message to use. In my projects the tradition is to use the OP as the commit message and edit it to always reflect the state of the PR.

**Pull request merged**
