### PR TITLE
[WIP] Generated PhantomData for used type parameters 

### PR DESCRIPTION
**Pull request by Kowasaki**
The test expectations shows all the generated ::std::marker::PhantomData<::std::cell::UnsafeCell<T>> used type parameters.

### CODE REVIEW

**Comment by fitzgen** [comment]
@Kowasaki thanks! This looks great!

There are just two things needed before we can merge this:

1. There are a couple test failures in CI where it seems not all the test expectations were updated: https://travis-ci.org/servo/rust-bindgen/jobs/222713799#L813 You can go ahead and look at the logged diffs to see which files and what test expectation changes are still needed.

2. Once that is done, please rebase on top of master and sqaush your work down into one commit.

Thanks again! Looking forward to landing this :)

**Comment by fitzgen** [comment]
@Kowasaki hi! do you need some help rebasing + squashing and resolving conflicts?

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request is a good, quick read on how to rebase + squash a pull request.

**Comment by KiChjang** [comment]
A more lengthy guide is [here](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) in servo's repository's wiki.

**Comment by Kowasaki** [comment]
Hey all,

Thanks for the guides! I think I am still doing rebasing/squashing wrong though since I can still see all the commits here... it looks like I did squash the commits on my repo but I am not sure what is going on here

**Comment by fitzgen** [comment]
Rebased + squashed in #689

**Pull request closed without merging**
