### PR TITLE
Version bump, ignore expectations' Cargo.lock

### PR DESCRIPTION
**Pull request by emilio**
r? @fitzgen or @Yamakaky

### CODE REVIEW

**Comment by fitzgen** [comment]
@bors-servo r+

Make sure to push a tag for the version too!

**Comment by Yamakaky** [comment]
Where can I see the available bors commands?

**Comment by KiChjang** [comment]
@Yamakaky build.servo.org/homu, but you need to first have reviewer privileges before you can issue commands to bors-servo. Maybe @emilio can help you with this.

**Comment by emilio** [comment]
Yeah, usually you do at least a few reviews before getting reviewer privileges though

**Comment by heycam** [comment]
I guess the test jobs fail due to the `git diff-index --quiet HEAD` command.  What's the purpose of that?  Given that two commands previously we do a `git add -A`, and add changes to the index, it seems like this will always report that there is a difference between HEAD and the index and return with exit code 1.

**Comment by fitzgen** [comment]
> I guess the test jobs fail due to the git diff-index --quiet HEAD command. What's the purpose of that? Given that two commands previously we do a git add -A, and add changes to the index, it seems like this will always report that there is a difference between HEAD and the index and return with exit code 1.

This is to check that regenerating the test expectations does not introduce any unexpected changes. The `git add -A` shouldn't result in anything getting added because there shouldn't be any changes. The diff exits non-zero if there are any changes.

As for why changes seem to be added here, I am not sure. Let me take a look.

**Comment by fitzgen** [comment]
Hmmm... because we pass `--quiet` there isn't much to investigate :-/

**Comment by heycam** [comment]
The `git diff @` command right before it and the `git diff-index HEAD` should be looking at the same differences, shouldn't they?

**Comment by emilio** [comment]
Yup, just forgot to build after the version bump, so the cargo.lock needed to be updated.

@bors-servo r=fitzgen

**Pull request merged**
