### PR TITLE
Make the switch to LLVM3.9.

### PR DESCRIPTION
**Pull request by emilio**
r? @nox

I don't know if this will pass CI yet, let's see.

### CODE REVIEW

**Comment by emilio** [comment]
CI is blocked on https://github.com/travis-ci/apt-source-whitelist/issues/300

**Comment by nox** [comment]
@emilio https://github.com/Dobiasd/FunctionalPlus/pull/49

**Comment by fitzgen** [comment]
What's the status of this? How eager are we to force llvm 3.9 and get rid of the `llvm_stable` feature?

**Comment by emilio** [comment]
This is no longer relevant with runtime-libclang.

**Pull request closed without merging**
