### PR TITLE
ir: Remove unused call to clang_Cursor_isAnonymous.

### LINKED ISSUE #496: Clang version is hardcoded in Cargo.toml
I'm getting errors such as 

> function not loaded: clang_Cursor_isAnonymous

because I have clang 3.5 (and unfortunately I can't upgrade it on that machine).

I'm not sure how can I use bindgen with an older version, given that it seems to be hardcoded to use 3.9:

https://github.com/servo/rust-bindgen/blob/8264afa875d686688680123859f8820e19c8028c/Cargo.toml#L42

### PR DESCRIPTION
**Pull request by emilio**
Fixes #496

### CODE REVIEW

**Comment by emilio** [comment]
Self-reviewing, trivial enough.

@bors-servo r+

**Comment by KiChjang** [comment]
@bors-servo r-

Not trivial enough; Travis is failing.

**Comment by emilio** [comment]
r? @KiChjang 

Forgot to remove one call in the logging code.

**Pull request merged**
