### PR TITLE
Gate on libclang 4 CI passing :)

### PR DESCRIPTION
**Pull request by fitzgen**
Need those test expectation diffs across libclang versions from Travis CI...

### CODE REVIEW

**Comment by fitzgen** [comment]
CI is green with libclang 4 🎉 🎉 🎉

r? @emilio

**Comment by emilio** [comment]
I'm wary of how this will turn out in order to update tests, but it's probably fine, and the extra test coverage is more than worth it.

@bors-servo r+

**Comment by fitzgen** [comment]
> I'm wary of how this will turn out in order to update tests, but it's probably fine, and the extra test coverage is more than worth it.

I just went through the process (I don't have libclang 4 installed) and it wasn't so bad.

**Comment by fitzgen** [comment]
nor libclang 3.8 installed for that matter

**Pull request merged**
