### PR TITLE
Re-enable OSX builds on Travis CI

### PR DESCRIPTION
**Pull request by emilio**
This reverts commit fc38f9b18a9dacc76b7e8a5c8633f0f02289daae.

r? @fitzgen

### CODE REVIEW

**Comment by fitzgen** [comment]
Hooray for long build times! \o/

@bors-servo r+

**Comment by scoopr** [comment]
It seems travis is having issues with mac hosts, hence the delay
https://www.traviscistatus.com/incidents/k79mjcv403c4

**Comment by emilio** [comment]
@bors-servo r=fitzgen

 * There were a few zombie builds on travis

**Pull request merged**
