### PR TITLE
Add union tutorial

### PR DESCRIPTION
**Pull request by jamesmunns**
Here is a first addition to describe usage of unions. Please let me know if there are any changes you would like, or additional features to cover.

For now, I have described both ways to interact with unions, as the new union type has not stabilized.

### CODE REVIEW

**Comment by fitzgen** [comment]
Oh, you may need to add **ignore** to the rust code snippets introduced, as CI is compiling them as if they were doctests, which will likely cause compilation failures in this case.

    ```rust,ignore
    <code snippet>
    ```

Ping me again when you've done that and I can r+ again if needed.  Thanks!

**Comment by jamesmunns** [comment]
@fitzgen added a section for CLI/Lib items, as well as fixed the snippets.

**Comment by emilio** [comment]
Trying to wake up homu.

**Pull request merged**
