### PR TITLE
codegen: Always implement debug for __BindgenUnionField.

### LINKED ISSUE #246: Debug derived when not allowed
Eg change `tests/headers/union_with_big_member.h` like this:

    -  int b[33];
    +  char b[33];

Then the output is like this:

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct WithBigArray {
    pub a: __BindgenUnionField<::std::os::raw::c_int>,
    pub b: __BindgenUnionField<[::std::os::raw::c_char; 33usize]>,
    pub bindgen_union_field: [u32; 9usize],
}
```

But the array `b` of __BindgenUnionField` is too large for `#[derive(Debug)]` to be allowed.

I hit this with a header file that pulls in `pthreads`: in particular

````c
union pthread_attr_t
{
  char __size[__SIZEOF_PTHREAD_ATTR_T];
  long int __align;
};
````

### PR DESCRIPTION
**Pull request by emilio**
Our debug-detection code assumes so.

Fixes #246

r? @fitzgen

### CODE REVIEW

**Comment by fitzgen** [comment]
@emilio you did delegate "fizgen" not "fi**t**zgen", so I can't approve.

**Comment by emilio** [comment]
Yikes, sorry :/

@bors-servo r=fitzgen

**Pull request merged**
