### PR TITLE
Avoid superfluous repeated builds on Travis

### PR DESCRIPTION
**Pull request by jdub**
Another fix to greatly improve test suite turnaround times.

### CODE REVIEW

**Comment by jdub** [comment]
Comparing #204 to #265:
- ~13 minutes to ~8 minutes on stable
- ~19 minutes to ~11 minutes on nightly (llvm_stable)
- ~17 minutes to ~12 minutes on nightly

**Comment by emilio** [comment]
Let's disable building on nightly until https://github.com/rust-lang/rust/issues/37786 is resolved.

**Comment by fitzgen** [comment]
> Let's disable building on nightly until rust-lang/rust#37786 is resolved.

I added a ride along commit to #264 that does this.

**Pull request merged**
