### PR TITLE
force pad bytes before field with large aligement

### PR DESCRIPTION
**Pull request by flier**
Seems a regression issue to place a field with large aligement.

### CODE REVIEW

**Comment by flier** [comment]
>    Updating registry `https://github.com/rust-lang/crates.io-index`
>error: failed to load source for a dependency on `objc`
>Caused by:
>  Unable to update registry https://github.com/rust-lang/crates.io-index
>Caused by:
>  failed to fetch `https://github.com/rust-lang/crates.io-index`
>To learn more, run the command again with --verbose.
>The command "BINDGEN_FEATURES="$BINDGEN_FEATURES" ./ci/test.sh" exited with 101.

**Comment by emilio** [comment]
Ok, this is green, I'm merging manually, since the OSX builders seem to have network problems.

**Pull request merged**
