### PR TITLE
Append the input header to the end of the clang args, instead of the front

### PR DESCRIPTION
**Pull request by fitzgen**
r @emilio

### CODE REVIEW

**Comment by Manishearth** [comment]
This causes clang to complain with `error: language not recognized: ''`

**Comment by fitzgen** [comment]
> This causes clang to complain with error: language not recognized: ''

With what command? I verified manually that the `rust-mozjs/etc/bindings.sh` script works with this change.

**Comment by emilio** [comment]
Yes, that's correct. What Stylo was doing (to workaround the behavior before this patch), was using the filename after clang-flags.

I think this confused docopt, that thought that the input header was other thing, and when we pushed it to `clang_args`, well, clang got confused.

But it's not this patch's bug per se.

**Comment by bholley** [comment]
Yes, but stylo binding generation is still broken. What is the fix?

**Comment by emilio** [comment]
@bholley: https://github.com/Manishearth/servo/commit/197c684a3265d0a5f7c4c985694411e2d6b7dbd8

**Pull request merged**
