### PR TITLE
travis: try to fix build

### PR DESCRIPTION
**Pull request by emilio**

### CODE REVIEW

**Comment by emilio** [comment]
tl; dr; llvm repos are back, so the ugly hacks that downloaded a release are no longer necessary, but we still need to build with llvm 3.8 for testing.

**Comment by nox** [comment]
@emilio Why not just install LLVM 3.8?

**Comment by nox** [comment]
Err, 3.9...

**Comment by emilio** [comment]
I *think* it's not released yet, but I'll try.

**Comment by nox** [comment]
Yes it isn't, but they provide nightly builds for all platforms we care about IIRC.

**Comment by emilio** [comment]
Yes, you're right, though they're disallowed by travis (see https://travis-ci.org/emilio/rust-bindgen/builds/140548819).

Also, we probably want to build with llvm stable for stylo, since the 3.9-only patches are not needed, and installing llvm3.9 can be a pain in some OSes.

**Pull request merged**
