### PR TITLE
Replace all non-fatal `error!`s with `warn!`s

### PR DESCRIPTION
**Pull request by saneyuki**
This fix https://github.com/servo/rust-bindgen/issues/368

### CODE REVIEW

**Comment by saneyuki** [comment]
This patch does not replace these `error!`:
	- https://github.com/servo/rust-bindgen/blob/d49bae228ca346e0e1e8d49d223b1207caece543/libbindgen/src/ir/ty.rs#L691
	- https://github.com/servo/rust-bindgen/blob/d49bae228ca346e0e1e8d49d223b1207caece543/libbindgen/src/ir/ty.rs#L872
	- https://github.com/servo/rust-bindgen/blob/d49bae228ca346e0e1e8d49d223b1207caece543/libbindgen/src/ir/item.rs#L961
	- https://github.com/servo/rust-bindgen/blob/d49bae228ca346e0e1e8d49d223b1207caece543/libbindgen/src/ir/context.rs#L650-L654

**Comment by saneyuki** [comment]
> https://github.com/servo/rust-bindgen/blob/d49bae228ca346e0e1e8d49d223b1207caece543/libbindgen/src/ir/context.rs#L650-L654

@fitzgen  Should I replace this `error!` too?

**Comment by fitzgen** [comment]
> > https://github.com/servo/rust-bindgen/blob/d49bae228ca346e0e1e8d49d223b1207caece543/libbindgen/src/ir/context.rs#L650-L654
> 
> @fitzgen Should I replace this `error!` too?

I think it is fine leaving this one as-is.

**Pull request merged**
