### PR TITLE
Fix #140 clang::Type::arg_types should return Option<Vec<Type>>

### LINKED ISSUE #140: clang::Type::arg_types should return Option<Vec<Type>>
`arg_types` makes FFI calls that are only valid if this type is a function type. We should check whether or not this type is a function type, and if it is not, then return `None`. If it is, we should proceed with the FFI calls and return `Some`.

This will make it so that every caller doesn't have to remember to do the check, which removes a foot gun if they forget.

I can mentor whoever would like to work on this bug.

### PR DESCRIPTION
**Pull request by rloisel**
Fixes #140

### CODE REVIEW

**Comment by fitzgen** [comment]
Looks like this is going to need to be rebased over the introduction of `rustfmt`ing our code, sorry!

Did you rebuild and re-run tests? I would expect that there would compilation errors where callers were not expecting the newly introduced option.

**Comment by rloisel** [comment]
Yeah, I was able to build and test without issue.
I used : `cargo test --features llvm_stable` and `cargo build --features llvm_stable`

I dont understand, what is the issue ? what should I do ?

**Comment by fitzgen** [comment]
Oh hm. It seems we aren't calling this function anywhere anymore.

The changes look good to me, but I wonder if we're better off removing the dead code. @emilio, thoughts?

**Comment by fitzgen** [comment]
@rloisel I just talked to emilio on irc, and we think the best thing to do is to delete this method. Sorry for making you jump through a few different hoops! Would you like to morph this PR into the removal of the method? If not, I can do it and we can find you another issue that is maybe more fun.

**Comment by rloisel** [comment]
@fitzgen No worries :). I will do the update to remove the function.

**Comment by emilio** [comment]
Still needs a rebase unfortunately, do you need any help with it? If so, please let us know :)

**Comment by rloisel** [comment]
Hum yeah. I'm not very familiar with rebasing.
Should I do a `git rebase origin/master` on my fix branch ?

**Comment by KiChjang** [comment]
You'll first need to be on your branch, then `git fetch upstream master`, then `git rebase upstream/master`. You're going to run into a merge conflict right after rebase, do you have the necessary tools to solve it or do you think you can solve it manually?

**Comment by rloisel** [comment]
Thanks for your help.

I did a `git fetch origin master` on my fix branch, but its updating my copy of src/clang.rs.
I have to commit the file before rebasing, is it normal ?

**Comment by KiChjang** [comment]
Yes, because both you and upstream have modified `src/clang.rs`, which causes a merge conflict, and git needs to know what the final version of the file should look like, hence a new commit is necessary (unless you decide to either ignore your changes or upstream's changes, in which case, no new commits are necessary). It should automatically create a new commit for you when you do `git rebase --continue` after resolving merge conflicts. If it doesn't, please do NOT use `git commit`. Ask us here or in #servo on `irc.mozilla.org` if things get too hairy.

Once you're done with the rebase, `git status` should show you that your local branch and your fork differs by 1 commit. This is normal. What you need to do next is to `git push -f` to your fork's branch to override its commit history with your local branch's commit history. Does that make sense?

**Comment by KiChjang** [comment]
You seem to have done the rebase wrong. I should have really asked: how many remotes do you have locally? You mentioned `origin/master` but I specifically indicated that you should fetch from `upstream/master`.

**Comment by rloisel** [comment]
Ah I see the issue, I think.
I didnt add upstream remote to my local repo. So I thought when you said upstream it was referring to my fork origin :s.

Better to close the PR and create a new one from a new branch (as its a very small update) ?

**Comment by emilio** [comment]
That'd be fine if you wish, though `git reflog` + `git reset` may give you back to where you started too :)

**Pull request closed without merging**
