### PR TITLE
Pass the potential id to be used as the type wrapper id, and prevent leaving a dangling a type parsing template aliases.

### PR DESCRIPTION
**Pull request by emilio**
This should fix the MSVC problems @upsuper has been having.

@upsuper, can you confirm if this fixes the panic you were hitting?

### CODE REVIEW

**Comment by upsuper** [comment]
No, it doesn't seem to fix that issue.

**Comment by emilio** [comment]
Maybe the next one does, I'm trying to build a test-case now.

**Comment by emilio** [comment]
Rebased (a while ago). r? @nox

**Comment by emilio** [comment]
(btw, the second patch makes the MSVC panic go away)

**Comment by emilio** [comment]
Actually, @fitzgen, may you also be interested in reviewing this? :)

**Comment by emilio** [comment]
Yep, added a test.

The `Trace` thing sounds good, it mostly duplicates `TypeCollector`, so it'd be nice to share logic there.

I also added a test for #3, which is r=me.

@bors-servo: r=fitzgen,emilio

**Pull request merged**
