### PR TITLE
Use c_schar instead of c_char

### PR DESCRIPTION
**Pull request by pyropeter**
The signedness of the C type 'char' is implementation defined. The
rust type c_schar exists for this reason. Use it.

### CODE REVIEW

**Comment by nox** [comment]
The type `c_schar` is always signed, whereas `c_char`'s signedness is implementation-defined. Where did you read that `c_schar` was to be used for the equivalent of C's `char` type?

**Comment by pyropeter** [comment]
I didn't. But bindgen uses `c_char` for clangs `CXType_SChar`, which is obviously a `signed char`.

**Comment by nox** [comment]
That sounds wrong indeed. It seems like `IntKind` should have an additional variant `SChar`.

**Comment by emilio** [comment]
> That sounds wrong indeed. It seems like IntKind should have an additional variant SChar.

That's right. Please update the PR to do that instead, thanks!

**Comment by pyropeter** [comment]
Why do you want to have an additional variant `SChar` in `IntKind`? As far as I understand it, clang takes care of the ugly `char` type and only uses `signed char` and `unsigned char` afterwards, so there really is no need for a variant representing `char`, is there?

One could of course rename the `Char` variant to `SChar`, but that would break the naming scheme of your variants. In that case I would prefer to add an explicit `S` prefix to all signed variants. (Like it is done in clang)

**Comment by emilio** [comment]
> Why do you want to have an additional variant SChar in IntKind? As far as I understand, clang takes care of the ugly char type and only uses signed char and unsigned char afterwards, so there really is no need for a variant representing char, is there?

Whoops, you're totally right here. My memory failed me and I thought that there was a `CXType_Char`, but apparently there isn't, so this looks fine to me.

@bors-servo r+

**Pull request merged**
