### PR TITLE
Remove unused template_arg_kind

### PR DESCRIPTION
**Pull request by jcdyer**
Addresses #133

### CODE REVIEW

**Comment by jcdyer** [comment]
My usual development laptop is out of commission, and I'm working through some dependencies to actually get llvm installed on the one I'm using.  As such, I haven't actually been able to build with this code yet.  I'll update when I do.

**Comment by jcdyer** [comment]
Well, I'm able to build successfully, but if I run tests, either with my change or without, I get 108 errors, including the following:

```
child stderr> dyld: Library not loaded: @rpath/libclang.dylib
child stderr>   Referenced from: /Users/cliffdyer/src/rust-bindgen/target/debug/bindgen
child stderr>   Reason: image not found
child stderr> Traceback (most recent call last):
child stderr>   File "/Users/cliffdyer/src/rust-bindgen/tests/tools/run-bindgen.py", line 185, in <module>
child stderr>     main()
child stderr>   File "/Users/cliffdyer/src/rust-bindgen/tests/tools/run-bindgen.py", line 179, in main
child stderr>     args.rust_bindings)
child stderr>   File "/Users/cliffdyer/src/rust-bindgen/tests/tools/run-bindgen.py", line 131, in generate_bindings
child stderr>     run_cmd(command, cwd=os.getcwd(), env=make_bindgen_env())
child stderr>   File "/Users/cliffdyer/src/rust-bindgen/tests/tools/run-bindgen.py", line 122, in run_cmd
child stderr>     subprocess.check_call(command, **kwargs)
child stderr>   File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
child stderr>     raise CalledProcessError(retcode, cmd)
child stderr> subprocess.CalledProcessError: Command '['/Users/cliffdyer/src/rust-bindgen/target/debug/bindgen', '-o', '/Users/cliffdyer/src/rust-bindgen/tests/expectations/whitelist_vars.rs', '--dummy-uses', '/Users/cliffdyer/src/rust-bindgen/tests/uses/whitelist_vars.c', '--no-unstable-rust', '--raw-line', '', '--raw-line', '#![allow(non_snake_case)]', '--raw-line', '', '/Users/cliffdyer/src/rust-bindgen/tests/headers/whitelist_vars.h']' returned non-zero exit status -6
```

**Comment by fitzgen** [comment]
@jcdyer, are you running the tests with `DYLD_LIBRARY_PATH` and `LIBCLANG_PATH` set? That error seems to be `dyld` complaining that it can't find `libclang`.

**Comment by fitzgen** [comment]
The change looks good, however I guess we aren't using this method anywhere? In that case, we should remove it. @jcdyer, would you like to evolve this PR into the method removal?

**Comment by jcdyer** [comment]
@fitzgen That fixed the issue.  I needed to use:

     DYLD_LIBRARY_PATH=$llvmlib LIBCLANG_PATH=$llvmlib cargo test --features=llvm_stable

I've updated the PR to remove the function instead of changing the return type.

**Comment by emilio** [comment]
This needs a rebase it seems.

**Comment by jcdyer** [comment]
Rebased.

**Comment by emilio** [comment]
@bors-servo r+ 

Thanks!

**Comment by fitzgen** [comment]
Thanks @jcdyer!

**Pull request merged**
