### PR TITLE
Deduplicate submodules

### LINKED ISSUE #292: Duplicate modules in generated bindings with --enable-cxx-namespaces
```
$ ./target/debug/bindgen ./input.hpp --enable-cxx-namespaces
```

Input:

```c++
namespace std {}
namespace std {}
```

Output:

```rust
/* automatically generated by rust-bindgen */

pub mod root {
    #[allow(unused_imports)]
    use root;
    pub mod std {
        #[allow(unused_imports)]
        use root;
    }
    pub mod std {
        #[allow(unused_imports)]
        use root;
    }
}
```

### PR DESCRIPTION
**Pull request by fitzgen**
C++ allows many `namespace foo { ... }` forms in the source, and they
all end up referring to the same `foo` namespace. We need to make sure
that the submodules we generate when parsing these namespaces end up
referring the same module as well, rather than different submodules.

Fixes #292.

r? @emilio

### CODE REVIEW

**Comment by fitzgen** [comment]
The `RefCell` isn't pretty... I'm open to suggestions for alternatives.

**Comment by emilio** [comment]
So the idea was that this piece of code:

```rust
         let cursor = cursor.canonical();
         if let Some(id) = self.modules.get(&cursor) {
             return *id;
         }
```

Would do the work of de-duplicating them. That would work nicely, of course, if we ever filled the modules map.

So I think the following patch would just do the same, and it is arguably better:

```diff
diff --git a/libbindgen/src/ir/context.rs b/libbindgen/src/ir/context.rs
index 7c643f0..76e2784 100644
--- a/libbindgen/src/ir/context.rs
+++ b/libbindgen/src/ir/context.rs
@@ -888,6 +888,8 @@ impl<'ctx> BindgenContext<'ctx> {
                                self.current_module,
                                ItemKind::Module(module));
 
+        self.modules.insert(cursor, module.id());
+
         self.add_item(module, None, None);
 
         module_id
```

**Comment by emilio** [comment]
I'm trying to land that fix in #295 since I plan to fix the stylo build today, and this might be required.

**Comment by fitzgen** [comment]
> So the idea was that this piece of code:

Ah, I see. I didn't realize that the different `namespace foo { ... }` declarations would end up with the same cursor.

**Comment by emilio** [comment]
They don't, but they have the same _canonical_ cursor, which is what we use to index them.

**Comment by fitzgen** [comment]
> They don't, but they have the same canonical cursor, which is what we use to index them.

Gotcha. Might be worth adding comments and also asserting that `cursor.canonical() == cursor` when we add to the modules map.

**Pull request closed without merging**
