### PR TITLE
Speed up integration tests (move building expectations)

### PR DESCRIPTION
**Pull request by jeanphilippeD**
Speed up running 'cargo test':
-Before: 2'17s
-After: 30s

Update to use new path:
Makefile, .travis.yml, CONTRIBUTING.md, tests/tests.rs

Delete unused expectation that fail to compile:
tests/expectations/moar_bitfields.rs
tests/expectations/variadic_template_args.rs

### CODE REVIEW

**Comment by emilio** [comment]
This looks good, but needs documentation, and being added to CI.

**Comment by jeanphilippeD** [comment]
Thank you very much for your review.

I've updated all the places I found that mentioned expectations.
`$ cargo test -p tests_expectations` shows up in the travis job output.

**Comment by emilio** [comment]
@bors-servo r+ 

Looks good, thanks!

**Comment by jdub** [comment]
Hmm, I'm working on #204, and having trouble running these tests on Windows. I've made sure Rust's `gcc.exe` and `ld.exe` are in my `PATH` ahead of msys2's mingw ones, but it can't link with `gcc`.

https://gist.github.com/jdub/66752599b85d73b15d12a7d7fd985959

Works fine on Linux. And this *is* a cool change!

**Comment by jeanphilippeD** [comment]
Hello,
My understanding is rustbindgen_py before would have done:
```
$ rustc --test pathToGeneratedRust/class_with_typedef.rs -o tempFile
$ tempFile  # execute the tempFile
```
Is it different when using `cargo test`?
It seems for whatever reason here, the linker on windows does not discard unused functions symbols here.

Does the link error occurs as well when you do:
```
$ rustc --test tests/expectations/tests/class_with_typedef.rs
$ ./class_with_typedef.exe
```

**Comment by jdub** [comment]
Yeah, same error. Don't worry too much -- none of this was expected to work on Windows, and it's almost certainly an installation problem. Thanks.

btw, between your changes and mine, we've reduced test suite time (excluding build) on my machine from about 21s to 2s. 😆 😆 😆 

```
D:\GitHub\rust-bindgen\libbindgen [logless-library ≡]> rustc --test .\tests\expectations\tests\class_with_typedef.rs
warning: type `C_MyInt` should have a camel case name such as `CMyint`, #[warn(non_camel_case_types)] on by default
  --> .\tests\expectations\tests\class_with_typedef.rs:17:1
   |
17 | pub type C_MyInt = ::std::os::raw::c_int;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: type `C_Lookup` should have a camel case name such as `CLookup`, #[warn(non_camel_case_types)] on by default
  --> .\tests\expectations\tests\class_with_typedef.rs:18:1
   |
18 | pub type C_Lookup = *const ::std::os::raw::c_char;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\crt2.o" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "class_with_typedef.0.o" "-o" "class_with_typedef.exe" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libtest-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgetopts-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libterm-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcollections-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_unicode-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc_system-5c6cf767.rlib" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-5c6cf767.rlib" "-l" "kernel32" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-l" "advapi32" "-l" "gcc_eh" "-l" "compiler-rt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\jdub\\.multirust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: class_with_typedef.0.o:(.text+0x12f9): undefined reference to `C::method(int)'
class_with_typedef.0.o:(.text+0x132b): undefined reference to `C::methodRef(int&)'
class_with_typedef.0.o:(.text+0x135b): undefined reference to `C::complexMethodRef(char const*&)'
class_with_typedef.0.o:(.text+0x1389): undefined reference to `C::anotherMethod(int)'
ld: class_with_typedef.0.o: bad reloc address 0x18 in section `.xdata'
ld: final link failed: Invalid operation


error: aborting due to previous error

D:\GitHub\rust-bindgen\libbindgen [logless-library ≡ +2 ~0 -0 !]> which gcc
/c/Users/jdub/.multirust/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin/gcc
```

**Comment by emilio** [comment]
I bet it's not an installation problem, but that rustc may not be performing dead code elimination, which is what could cause those linker errors.

**Pull request merged**
