### PR TITLE
Parse negative integers appropriately

### PR DESCRIPTION
**Pull request by Wafflespeanut**
Instead of parsing a token at some specified index, we can parse the immediately found literal. Also, this allows negative integers to be parsed as `c_int`s (which is required for some of the constants).

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
It's necessary for including some constants from `gfxFontConstants.h`

**Comment by emilio** [comment]
Can you add a test for this? Adding a file under `tests/headers/` and running `make test` should do it. Thanks!

**Comment by Wafflespeanut** [comment]
Alright, I've made the changes :)

**Comment by emilio** [comment]
I think this is good to merge for now. IIRC upstream bindgen had integrated a C expression parser, so we might want to move to it.

Can you squash, then r=me?

**Comment by Wafflespeanut** [comment]
I've squashed the test commits, but I'd like to keep the first commit separately, since it makes changes to the code.

@bors-servo r=emilio

Thanks! :)

**Pull request merged**
