### PR TITLE
Followed Resolved Type Ref instead of panicking

### LINKED ISSUE #353: libbindgen fails with "How?"
The following code:
```c
typedef void (Tcl_FSDupInternalRepProc) ();
extern Tcl_FSDupInternalRepProc TclNativeDupInternalRep;
```

Triggers the "How?" panic in `libbindgen/src/codegen/mod.rs:2008` reproduced here:
```rust
        let signature = match *signature.kind() {
            TypeKind::Function(ref sig) => sig,
            _ => panic!("How?"), // << This line
        };
```

Changing it to:
```rust
        let signature = match *signature.kind() {
            TypeKind::Function(ref sig) => sig,
            ref ty => panic!("How? {} {:?}", name, ty), // << This line
        };
```

Outputs: `How? TclNativeDupInternalRep ResolvedTypeRef(ItemId(1))`

I was hoping to use libbindgen to move away from Tcl without needed to jump to C++, but the above declaration style is used all over the Tcl headers. (It's of course been cleaned up, macros and extra typedefs removed).

### PR DESCRIPTION
**Pull request by Nashenas88**
This could fix #353, but I would really want everyone to review in case I'm missing something important. The compilation continues for the code I'm working with. Also, should I add a regression test for this? I could simply use the code in the referenced issue.

### CODE REVIEW

**Comment by fitzgen** [comment]
r? @emilio 

I feel like we need a variant of the various  `resolve_foo` context methods that automatically follows resolved type refs (and maybe aliases as well?). We can spot fix issues like this one, but it would be nice if we had a more base solution for the 99% case.

**Comment by fitzgen** [comment]
Also, thanks for the pull request, @Nashenas88 :)

**Comment by fitzgen** [comment]
> Also, should I add a regression test for this? I could simply use the code in the referenced issue.

Yes, that would be great.

**Comment by emilio** [comment]
> I feel like we need a variant of the various resolve_foo context methods that automatically follows resolved type refs (and maybe aliases as well?). We can spot fix issues like this one, but it would be nice if we had a more base solution for the 99% case.

We do have that, which is the `canonical_type` thing. We could/should use that here. We need to publish a new version, so let's merge this and I'll get that cleaned up before publishing.

@bors-servo r+

Thanks for the PR @Nashenas88! :)

**Pull request merged**
