### PR TITLE
Have tests pass on Windows

### PR DESCRIPTION
**Pull request by upsuper**
These changes allow `cargo test` to pass on Windows.

There are two followup work we should do at some point:
* setup AppVeyor so that we don't break Windows development either
* convert `no_system_header_includes` to be pure Rust so that it supports Windows natively

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Thanks a _lot_ for this Xidorn! :heart:

**Comment by fitzgen** [comment]
@upsuper awesome! Thanks! The faster appveyor is set up, the less likely this is to regress in the future. Do you have experience with appveyor (I don't)? If so, would you be willing to set it up for us? Thanks again!

**Comment by upsuper** [comment]
I don't either, unfortunately...

**Comment by emilio** [comment]
I know @uk992 has helped a lot with servo's appveyor integration. A hand here would be quite nice if he could! (no worries if not)

**Pull request merged**
