### PR TITLE
[WIP] Template instantiation layout test name mangling

### PR DESCRIPTION
**Pull request by fitzgen**
work in progress fix for #619 

It seems we aren't ever getting the mangled name out of libclang for template instantiations in practice, so we're hitting the fallback behavior (master's current behavior) 100% of the time :-/

Someone feel free to steal this from me, I'm not planning on investigating further in the near future.

### CODE REVIEW

**Comment by fitzgen** [comment]
cc @upsuper @Manishearth

**Comment by emilio** [comment]
I suspect the "completely instantiated template" check may not work as greatly for non-functions?

**Comment by upsuper** [comment]
Can we give this a higher priority? It is pretty painful to land patches when you push the numbers a bit via including a new file...

**Comment by fitzgen** [comment]
I don't personally have the cycles to work on this. Feel free to take over.

**Comment by emilio** [comment]
I put some other approach to this in #708

**Pull request closed without merging**
