### PR TITLE
Only load libclang once, and don't unload it

### PR DESCRIPTION
**Pull request by fitzgen**
See the first commit for details.

Second commit is just `cargo fmt`.

r? @emilio

### CODE REVIEW

**Comment by emilio** [comment]
Makes sense.

@bors-servo r+

**Comment by emilio** [comment]
Thanks for digging into it! :)

**Comment by nox** [comment]
Noooooo. https://doc.rust-lang.org/nightly/std/sync/struct.Once.html Please use that instead of lazy_static...

**Comment by fitzgen** [comment]
> Noooooo. https://doc.rust-lang.org/nightly/std/sync/struct.Once.html Please use that instead of lazy_static...

How would we save `libclang` in a global for other threads to reuse with `Once`?

**Pull request merged**
