### PR TITLE
Run tests on release builds

### PR DESCRIPTION
**Pull request by fitzgen**
This makes `cargo test` test the appropriate release/debug bindgen binary and extends Travis CI testing to also test release builds.

r? @emilio

### CODE REVIEW

**Comment by emilio** [comment]
Looks good to me, though travis doesn't agree... Let's try again...
@bors-servo r+

**Comment by fitzgen** [comment]
Interesting...

> thread 'run_bindgen_tests' panicked at '/home/travis/build/servo/rust-bindgen/target/release/bindgen is not a file! Build bindgen before running tests.', tests/tests.rs:74

**Comment by fitzgen** [comment]
I think I need to `if cfg!(debug_assertions)`

**Pull request merged**
